export const competitions = {
  "copa-catalunya-2026": {
    id: "copa-catalunya-2026",
    status: "completed",
    chapter: "01",
    season: "2026",
    competition: "Copa Catalunya Absolut",
    title: "COPA CATALUNYA ABSOLUT",
    date: "11 · 04 · 2026",
    location: "Barcelona, Spain",
    image: "./images/gallery/competitions/copa_catalunya_absolut_final.JPEG",
    medal: "silver",
    placement: "Silver · 2nd Place",
    category: "−90 KG",
    record: "3–1",
    totalMatTime: "07:04",
    ippons: "2",
    fastestWin: "00:42",
    competitors: "16",
    preparation: {
      story:
        "Write the complete story of your preparation, expectations and condition before this competition here.",
    },
    matches: [
      {
        number: "01",
        round: "ROUND ONE",
        outcome: "WIN",
        method: "IPPON",
        duration: "00:42",
        opponent: "OPPONENT TO BE ADDED",
        country: "COUNTRY OR CLUB",
        score: "SCORE TO BE ADDED",
        technique: "TECHNIQUE TO BE ADDED",
        shidos: "—",
        note: "Describe the decisive moment and how this match developed.",
        image: "",
        video: "",
      },
      {
        number: "02",
        round: "QUARTERFINAL",
        outcome: "WIN",
        method: "METHOD",
        duration: "00:00",
        opponent: "OPPONENT TO BE ADDED",
        country: "COUNTRY OR CLUB",
        score: "SCORE TO BE ADDED",
        technique: "TECHNIQUE TO BE ADDED",
        shidos: "—",
        note: "Describe the decisive moment and how this match developed.",
        image: "",
        video: "",
      },
      {
        number: "03",
        round: "SEMIFINAL",
        outcome: "WIN",
        method: "METHOD",
        duration: "00:00",
        opponent: "OPPONENT TO BE ADDED",
        country: "COUNTRY OR CLUB",
        score: "SCORE TO BE ADDED",
        technique: "TECHNIQUE TO BE ADDED",
        shidos: "—",
        note: "Describe the decisive moment and how this match developed.",
        image: "",
        video: "",
      },
      {
        number: "04",
        round: "FINAL",
        outcome: "LOSS",
        method: "METHOD",
        duration: "00:00",
        opponent: "OPPONENT TO BE ADDED",
        country: "COUNTRY OR CLUB",
        score: "SCORE TO BE ADDED",
        technique: "TECHNIQUE TO BE ADDED",
        shidos: "—",
        note: "Describe what happened in the final and what decided the result.",
        image: "",
        video: "",
      },
    ],
    lessons: [
      {
        number: "01",
        title: "PATIENCE",
        text: "Write the first important lesson from this competition.",
      },
      {
        number: "02",
        title: "TRANSITIONS",
        text: "Write what this competition revealed about transitions and continuation.",
      },
    ],
    changes: [
      {
        before: "Describe one technical habit before the competition.",
        after: "Describe how your training or execution changed afterward.",
      },
      {
        before: "Describe a second weakness or limitation.",
        after: "Describe the adjustment that followed.",
      },
    ],
    progression: {
      eyebrow: "ACT 07 · PUT INTO PRACTICE",
      text: "Explain where the lessons from this competition appeared again in training or at the following event.",
      nextCompetitionId: "vila-salou-teams-2026",
      nextDate: "09 · 05 · 2026",
      nextTitle: "VILA SALOU TROPHY TEAMS",
      nextResult: "GOLD · 1ST PLACE",
    },
    navigation: {
      previous: null,
      next: {
        id: "super-copa-espana-barcelona-2026",
        date: "02 · 05 · 2026",
        title: "SUPER COPA DE ESPAÑA ABSOLUT",
      },
    },
  },
};
